#ifndef MTDCAMERACORE_GLOBAL_H
#define MTDCAMERACORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MTDCAMERACORE_LIBRARY)
#  define MTDCAMERACORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define MTDCAMERACORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MTDCAMERACORE_GLOBAL_H
